rabbitmq:
  enabled: true
  name: rabbitmq
  image:
    registry: docker.io
    image: library/rabbitmq
    version:
  plugins:
    - rabbitmq_prometheus
  additionalConfig: |

  persistence:
    storage: 3Gi
  resources:
    limits:
      memory: 3Gi
      cpu: '1'
    requests:
      memory: 3Gi
      cpu: '1'
  replicas: 1
  tls:
    enabled: false
    secretName: rabbitmq-certs
    disableNonTLSListeners: true
    dnsNames:
      # amqps: amqps.rabbitmq.com
      # management: management.rabbitmq.com
  rbac:
    enabled: false
    groups: []
    group: ''
  service: {}
  custom_lb_service:
    enabled: false
    loadBalancerClass: ""
  ciliumNetworkPolicy:
    enabled: false
prober:
  enabled: false
  name: rabbitmq-prober
  image:
    registry: ghcr.io
    image: vshn/rabbitmq-instance-chart/prober
    tag:
  probeInterval: '10'
  metricsPort: 8080
  useTLS: 'true'
  alerts:
    enabled: false
    syn_team: null
  resources:
    requests: {memory: '64Mi', cpu: '50m'}
    limits: {memory: '128Mi', cpu: '100m'}
  monitoring:
    interval: '10s'
    recordingRulesInterval: '10s'
monitoring:
  enabled: true
