{{- if and .Values.rabbitmq.enabled .Values.rabbitmq.ciliumNetworkPolicy.enabled }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.rabbitmq.name }}-allow-from-world
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.rabbitmq.name }}
  ingress:
    - fromEntities:
        - world
      toPorts:
        - ports:
            - port: "5671"
              protocol: TCP
            - port: "5672"
              protocol: TCP
{{- end }}
