{{- if and .Values.rabbitmq.enabled .Values.rabbitmq.custom_lb_service.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-rabbitmq-lb-service-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-rabbitmq-lb-service-manager
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["*"]
  - apiGroups: ["espejote.io"]
    resources: ["jsonnetlibraries"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-rabbitmq-lb-service-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-rabbitmq-lb-service-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-rabbitmq-lb-service-manager
    namespace: {{ .Release.Namespace }}
---
apiVersion: espejote.io/v1alpha1
kind: JsonnetLibrary
metadata:
  name: {{ .Release.Name }}-rabbitmq-lb-service
  namespace: {{ .Release.Namespace }}
spec:
  data:
    config.json: |
      {{- toPrettyJson .Values.rabbitmq.custom_lb_service | nindent 6 }}
---
apiVersion: espejote.io/v1alpha1
kind: ManagedResource
metadata:
  name: {{ .Release.Name }}-rabbitmq-lb-service
  namespace: {{ .Release.Namespace }}
  annotations:
    syn.tools/description: |
      This ManagedResource watches the Service created by the
      rabbitmq-operator for the RabbitmqCluster resource that's created by
      the Commodore component.

      The ManagedResource creates a copy of the RabbitmqCluster's primary
      service with `spec.type=LoadBalancer` and a user-configurable
      `spec.loadBalancerClass`. The values of `metadata.annotations`,
      `spec.ports` and `spec.selector` are copied from the
      operator-managed Service and updated whenever the operator makes any
      changes.
spec:
  applyOptions:
    force: true
  context:
    - name: services
      resource:
        apiVersion: v1
        kind: Service
        name: {{ .Values.rabbitmq.name }}
        namespace: {{ .Release.Namespace }}
  triggers:
    - name: service
      watchContextResource:
        name: services
    - name: jsonnetlib
      watchResource:
        apiVersion: espejote.io/v1alpha1
        kind: JsonnetLibrary
        name: {{ .Release.Name }}-rabbitmq-lb-service
        namespace: {{ .Release.Namespace }}
  serviceAccountRef:
    name: {{ .Release.Name }}-rabbitmq-lb-service-manager
  template: {{ tpl (.Files.Get "files/rabbitmq-lb-service.jsonnet") . | quote }}
{{- end }}
