{{- if and .Values.prober.enabled .Values.prober.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Values.prober.name }}-alerts
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: rabbitmq.alerts
      rules:
        - alert: RabbitMQDown
          expr: max by (job, cluster_id, namespace) (rabbitmq_functional_availability) == 0
          for: 2m
          labels:
            severity: warning
            syn_team: {{ .Values.prober.alerts.syn_team | quote }}
            syn: "true"
            syn_component: {{ .Chart.Name }}-{{ .Release.Name }}
          annotations:
            summary: RabbitMQ is down
            description: RabbitMQ in namespace {{ "{{ $labels.namespace }}" }} has been down for more than 1 minute
        - alert: RabbitMQProbeFailures
          expr: increase(rabbitmq_probe_failures_total[5m]) > 3
          for: 0m
          labels:
            severity: warning
            syn_team: {{ .Values.prober.alerts.syn_team | quote }}
            syn: "true"
            syn_component: {{ .Chart.Name }}-{{ .Release.Name }}
          annotations:
            summary: Multiple RabbitMQ probe failures
            description: RabbitMQ prober in namespace {{ "{{ $labels.namespace }}" }} has failed {{ "{{ $value }}" }} times in the last 5 minutes
{{- end }}
