{{- if .Values.rabbitmq.enabled }}
{{- $externalSecret := .Values.rabbitmq.externalSecret }}
{{- if and .Values.rabbitmq.defaultUser.username .Values.rabbitmq.defaultUser.password }}
  {{- $externalSecret = .Release.Name }}
{{- end }}
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: {{ .Values.rabbitmq.name }}
  namespace: {{ .Release.Namespace }}
spec:
  rabbitmq:
    additionalPlugins: {{ toYaml .Values.rabbitmq.plugins | nindent 6 }}
    additionalConfig: |
      {{- if not (contains "vm_memory_high_watermark.absolute" .Values.rabbitmq.additionalConfig) }}
      vm_memory_high_watermark.absolute = {{ .Values.rabbitmq.resources.limits.memory }}
      {{- end }}
      {{- with .Values.rabbitmq.additionalConfig }}
      {{ . | nindent 6 }}
      {{- end }}
  image: {{ .Values.rabbitmq.image.registry }}/{{ .Values.rabbitmq.image.image }}:{{ .Values.rabbitmq.image.version | default .Chart.AppVersion }}-alpine
  persistence:
    storage: {{ .Values.rabbitmq.persistence.storage }}
  replicas: {{ .Values.rabbitmq.replicas }}
  resources: {{ toYaml .Values.rabbitmq.resources | nindent 4 }}
  service: {{ toYaml .Values.rabbitmq.service | nindent 4 }}
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            securityContext: {}
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchLabels:
                        app.kubernetes.io/component: rabbitmq
                        app.kubernetes.io/name: {{ .Values.rabbitmq.name }}
                    topologyKey: kubernetes.io/hostname
  {{- if .Values.rabbitmq.tls.enabled }}
  tls:
    secretName: {{ .Values.rabbitmq.tls.secretName }}
    disableNonTLSListeners: {{ .Values.rabbitmq.tls.disableNonTLSListeners }}
  {{- end }}
  {{- if $externalSecret }}
  secretBackend:
    externalSecret:
      name: {{ $externalSecret }}
  {{- end }}

{{- end }}
