{{- if and .Values.rabbitmq.defaultUser.username .Values.rabbitmq.defaultUser.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.rabbitmq.username | b64enc | quote }}
  password: {{ .Values.rabbitmq.password | b64enc | quote }}
  connection_string: {{ printf "amqp://%s:%s@%s.%s.svc:%s" .Values.rabbitmq.username .Values.rabbitmq.password .Release.Name .Release.Namespace "5672" | b64enc | quote }}
  default_user.conf: {{ printf "default_user = %s\ndefault_pass = %s" .Values.rabbitmq.username .Values.rabbitmq.password | b64enc | quote }}
  host: {{ printf "%s.%s.svc" .Release.Name .Release.Namespace | b64enc | quote }}
  port: {{ "5672" | b64enc | quote }}
  provider: {{ "rabbitmq" | b64enc | quote }}
  type: {{ "rabbitmq" | b64enc | quote }}
{{- end }}
